import type {DecisionMemory} from '../types/decision';
import type {MeetingHistoryDetail, MeetingHistoryItem, MeetingSummaryResult} from '../types/meeting';

type MeetingHistoryPageProps = {items: MeetingHistoryItem[]; detail: MeetingHistoryDetail | null; summary: MeetingSummaryResult | null; memories: DecisionMemory[]; summaryBusy: boolean; onOpen: (id: string) => void; onGenerateSummary: () => void};

export function MeetingHistoryPage({items, detail, summary, memories, summaryBusy, onOpen, onGenerateSummary}: MeetingHistoryPageProps) {
  return <section className="history-page">
    <div className="knowledge-heading"><div><span className="eyebrow">Final Snapshot</span><h2>历史会议</h2><p>这里展示会议结束时被冻结的状态，不会随知识库或模型变化。</p></div></div>
    <div className="knowledge-layout">
      <div className="knowledge-list">{items.length === 0 && <p className="placeholder">还没有已结束的会议。</p>}{items.map(item => <article className="knowledge-row" key={item.id} onClick={() => onOpen(item.id)}><div><span className={`knowledge-status ${item.status === 'finalized' ? 'ready' : 'processing'}`}>{item.status === 'finalized' ? '已固化' : '待固化'}</span><strong>{item.title}</strong><small>{new Date(item.startedAt).toLocaleString()}</small></div></article>)}</div>
      <aside className="knowledge-detail history-detail">{!detail ? <p className="placeholder">选择一场历史会议查看 Final Snapshot。</p> : <><h3>{detail.meeting.title}</h3>{!detail.snapshot ? <p>会议已经结束，尚未固化。</p> : <><strong>会议目标</strong><p>{detail.snapshot.objective || '未识别明确目标'}</p><strong>最终转写</strong><p className="history-transcript">{detail.snapshot.transcript || '无转写内容'}</p><strong>最终关注</strong>{detail.snapshot.findings.length === 0 ? <p>无</p> : detail.snapshot.findings.map((item, index) => <p key={index}>{item.title}：{item.summary}</p>)}<strong>决策依据</strong>{detail.snapshot.evidence.length === 0 ? <p>无</p> : detail.snapshot.evidence.map(item => <p key={item.id}>{item.title} · {Math.round(item.score * 100)}%</p>)}<strong>对话记录</strong>{detail.snapshot.dialogue.length === 0 ? <p>无</p> : detail.snapshot.dialogue.map((item, index) => <p key={index}><b>{item.role === 'user' ? '用户' : 'DecisionOS'}：</b>{item.content}</p>)}<div className="summary-heading"><strong>结构化会议总结</strong>{!summary && <button className="secondary-button" onClick={onGenerateSummary} disabled={summaryBusy}>{summaryBusy ? '生成中…' : '生成总结'}</button>}</div>{summary && <section className="meeting-summary"><p>{summary.summary}</p><strong>已确认事实</strong>{summary.keyFacts.length ? <ul>{summary.keyFacts.map((item, index) => <li key={index}>{item.text}</li>)}</ul> : <p>无</p>}<strong>会议决策</strong>{summary.decisions.length ? <ul>{summary.decisions.map((item, index) => <li key={index}>{item.text}</li>)}</ul> : <p>本次会议未形成明确决策。</p>}{memories.length > 0 && <p className="memory-confirmed">✓ 已沉淀 {memories.filter(item => item.status === 'active').length} 条有效决策记忆</p>}<strong>后续行动</strong>{summary.actionItems.length ? <ul>{summary.actionItems.map((item, index) => <li key={index}>{item.text}</li>)}</ul> : <p>无</p>}<strong>未解决问题</strong>{summary.openIssues.length ? <ul>{summary.openIssues.map((item, index) => <li key={index}>{item.text}</li>)}</ul> : <p>无</p>}<small>{summary.diagnostics.extractionMode === 'llm' ? 'AI 提取 + 规则校验' : '规则提取'} · {summary.evidence.length} 条可追溯依据</small></section>}</>}</>}</aside>
    </div>
  </section>;
}
